{% set name = "aiidalab" %}
{% set version = "26.2.0" %}
{% set python_min = "3.9" %}
{% set sha256 = "146b2c5b779bf52bced1f9c952e70d35871b91176ee2ec59220d6db7a6a503ef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiidalab-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - aiidalab = aiidalab.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cachetools >=4.1,=4
    - click >=7.0,<9
    - click-spinner >=0.1,=0
    - dulwich >=0.20,=0
    - packaging >=20.1
    - pip
    - python >={{ python_min }}
    - requests >=2.27,=2
    - requests-cache >=1.0,=1
    - setuptools <82
    - tabulate >=0.8,=0
    - toml >=0.10,=0
    - traitlets >=5.0,=5
    - watchdog >=4.0,=4

test:
  imports:
    - aiidalab
  commands:
    - pip check
    - aiidalab --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aiidalab/aiidalab
  summary: Implements core functions of AiiDAlab.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - yakutovicha
    - unkcpz
    - danielhollas
